services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: "./backend/.env"
  nuxt:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
    environment:
      NUXT_PUBLIC_BACKEND_URL: "http://localhost/fastapi/"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    links:
      - fastapi
      - nuxt
    depends_on:
      - fastapi
      - nuxt
